name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build & push image
      run: |
        echo "${{secrets.DOCKERPW}}" | docker login -u "kinggstark" --password-stdin
        docker image build -t kinggstark/docker .
        docker push kinggstark/docker

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: pull & test image
      run: |
        echo "${{secrets.DOCKERPW}}" | docker login -u "kinggstark" --password-stdin
        docker run -e CI=true kinggstark/docker npm test
        

